### ISSUE TITLE
Certificate request contains redundant domain name which violates format required by Let's Encrypt

### ISSUE THREAD

**Issue by sven-ernw** [gardener/garden-setup#1279]
**What happened**:

The certificate request generated by ``garden-setup`` for the resource ``dashboard-identity-ingress`` contains the ingress domain as wildcard in _Dns Names_ (e.g., ``*.ing.gardener.gcp.example.com``) and a _Common Name_ (e.g., ``gardener.ing.gardener.example.com``) which is redundant to the wildcard domain. Such a request violates Let's Encrypt's requirements (or maybe even the ACME standard; the error is: ``urn:ietf:params:acme:error:malformed``) because a common name which is redundant with a wildcard domain is not allowed.

Consider the following ``arce.yaml`` configuration excerpt:

```yaml
acre:
  landscape:  
    name: example-gardener             # general Gardener landscape identifier, for example, `my-gardener`
    domain: gardener.gcp.example.com    # unique basis domain for DNS entries
// [...]
  cert-manager: 
    server: live                             # which kind of certificates to use for the dashboard/identity
// [...]
```

(Please note, I've replaced the original domain name with ``example.com``.)

This will generate the following Certificate resource in Kubernetes with the following configuration:

```yaml
  Common Name:  gardener.ing.gardener.example.com
  Dns Names:
    *.ing.gardener.gcp.example.com
```

which results in the following error from the Let's encrypt API:

```
obtaining certificate failed: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:malformed :: Error creating new order :: Domain name "gardener.ing.gardener.gcp.example.com" is redundant with a wildcard domain in the same request. Remove one or the other from the certificate request.
```

Full description of the generated Certificate resource:

```
% kubectl describe cert -n garden dashboard-identity-ingress
Name:         dashboard-identity-ingress
Namespace:    garden
Labels:       <none>
Annotations:  cert.gardener.cloud/class: garden-setup
API Version:  cert.gardener.cloud/v1alpha1
Kind:         Certificate
Metadata:
  Creation Timestamp:  2025-01-15T13:41:58Z
  Generation:          1
  Resource Version:    145282
  UID:                 40434f38-b77c-401d-87d0-859c2355286c
Spec:
  Common Name:  gardener.ing.gardener.example.com
  Dns Names:
    *.ing.gardener.gcp.example.com
  Issuer Ref:
    Name:  acme-issuer
  Secret Ref:
    Name:       identity-dashboard-tls
    Namespace:  garden
Status:
  Backoff:
    Observed Generation:  1
    Recheck After:        2025-01-15T13:49:22Z
    Recheck Interval:     4m0s
  Common Name:            gardener.ing.gardener.gcp.example.com
  Conditions:
    Last Transition Time:  2025-01-15T13:41:58Z
    Message:               obtaining certificate failed: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:malformed :: Error creating new order :: Domain name "gardener.ing.gardener.gcp.example.com" is redundant with a wildcard domain in the same request. Remove one or the other from the certificate request.
    Observed Generation:   1
    Reason:                Error
    Status:                False
    Type:                  Ready
  Dns Names:
    *.ing.gardener.gcp.example.com
  Issuer Ref:
    Cluster:               default
    Name:                  acme-issuer
    Namespace:             cert-manager
  Last Pending Timestamp:  2025-01-15T13:45:21Z
  Message:                 obtaining certificate failed: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:malformed :: Error creating new order :: Domain name "gardener.ing.gardener.gcp.example.com" is redundant with a wildcard domain in the same request. Remove one or the other from the certificate request.
  Observed Generation:     1
  State:                   Error
Events:
  Type     Reason     Age                  From                     Message
  ----     ------     ----                 ----                     -------
  Warning  sync       109s (x6 over 109s)  cert-controller-manager  waiting for end of pending rate limiting in 69 seconds
[...]
  Normal   reconcile  27s (x2 over 3m50s)  cert-controller-manager  certificate requested, preparing/waiting for successful DNS01 challenge
  Warning  reconcile  26s (x2 over 3m49s)  cert-controller-manager  obtaining certificate failed: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:malformed :: Error creating new order :: Domain name "gardener.ing.gardener.gcp.example.com" is redundant with a wildcard domain in the same request. Remove one or the other from the certificate request.
```

**What you expected to happen**:

Only the wildcard domain should be part of the Certificate resource. The following diff might resolve the issue:

```diff
diff --git a/components/cert-manager/cert/deployment.yaml b/components/cert-manager/cert/deployment.yaml
index c0df15e..9d1ce0b 100644
--- a/components/cert-manager/cert/deployment.yaml
+++ b/components/cert-manager/cert/deployment.yaml
@@ -26,8 +26,7 @@ cert:
         annotations:
           cert.gardener.cloud/class: (( imports.cert-controller.export.certClass ))
       spec:
-        commonName: (( .landscape.domains.identity_dns ))
-        dnsNames: (( .settings.certificate.domains ))
+        commonName: (( .settings.certificate.domains[0] ))
         secretRef:
           name: (( .settings.certificate.secret_name ))
           namespace: (( .settings.certificate.namespace ))
```

**How to reproduce it (as minimally and precisely as possible)**:

Deploy a Gardener with ``garden-setup`` with cert-manager server ``live`` for a valid domain.

```yaml
acre:
  landscape:  
    name: example-gardener             # general Gardener landscape identifier, for example, `my-gardener`
    domain: gardener.gcp.example.com    # unique basis domain for DNS entries
// [...]
  cert-manager: 
    server: live                             # which kind of certificates to use for the dashboard/identity
// [...]
```

**Environment**:

- Version of garden-setup (release or commit): master / f6be2e63207be3e60371a550e2dd3a868fe89478
- Versions of components (only needed if you overwrote the defaults): same as the default
- Where does the underlying base cluster come from and which operating system does it use? GKE
- Which cloud provider is configured for the setup? GCP
