### ISSUE TITLE
error generating manifest: unresolved nodes:

### ISSUE THREAD

**Issue by lklkxcxc** [gardener/garden-setup#174]
**What happened**:
sow deploy -A
**What you expected to happen**:
`generating exports
2020/03/12 02:21:46 error generating manifest: unresolved nodes:
        (( sync(exec_uncached(command)) ))      in /mounted/root/jiawen/landscape/crop/components/ingress-controller/export.yaml        temp.target     ()      *sync timeout reached
        (( defined(.temp.target.ip) ? "A" : "CNAME" ))  in /mounted/root/jiawen/landscape/crop/components/ingress-controller/export.yaml        export.type     ()
        (( .temp.target.ip || .temp.target.hostname ))  in /mounted/root/jiawen/landscape/crop/components/ingress-controller/export.yaml        export.address  ()      -'.temp.target' unresolved
        (( .temp.target.ip || .temp.target.hostname ))  in /mounted/root/jiawen/landscape/crop/components/ingress-controller/export.yaml        export.address  ()      -'.temp.target' unresolved 
error classification:
 *: error in local dynaml expression
 @: dependent of or involved in a cycle
 -: depending on a node with an error
Error: processing exports`
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
acre.yaml some config:
```
landscape:
  name: svc-cluster-local
  domain: svc.cluster.local
  cluster:
    kubeconfig: ./kubeconfig
    iaas: openstack
    networks:
      pods: 100.64.0.0/10
      nodes: 172.16.55.0/24
      services: 10.96.0.0/12 # change to under actual undercloud service ip cidr
  iaas:
    - name: openstack
      type: openstack
      mode: seed
      region: RegionOne
      zones:
      - nova
      credentials: *openstack
      floatingPools:
      - name: public
      loadBalancerProviders:
      - name: haproxy
      extensionConfig:
        machineImages:
          - name: coreos
            versions:
              - image: coreos-2345.3.0
                version: 2345.3.0
          - name: ubuntu
            versions:
              - image: ubuntu-18.04
                version: 18.04
      machineImages:
        - name: coreos
          versions:
          - version: 2345.3.0
        - name: ubuntu
          versions:
          - version: "18.04"
      machineTypes:
        - name: 2C4G50G
          cpu: "2"
          gpu: "0"
          memory: 4Gi
          usable: true
          storage:
            class: ""
            type: default
            size: 50Gi
        - name: 4C8G50G
          cpu: "4"
          gpu: "0"
          memory: 8Gi
          usable: true
          storage:
            class: ""
            type: default
            size: 50Gi
```
**Environment**:

- Version of garden-setup (release or commit)
2.2.0-dev
- Versions of components (only needed if you overwrote the defaults)
- Where does the underlying base cluster come from and which operating system does it use?
- Which cloud provider is configured for the setup?
- Other:

**Comment by Diaphteiros** [comment]
Hm, I need some additional information on that one. 

What happens here is that during the export step, the `ingress-controller` component tries to fetch the loadbalancer IP or hostname from the newly created ingress-controller service. The command used for that is something like `kubectl -n <service namespace> get service <service name> -o json`. This command is repeated until `status.loadBalancer.ingress.[0]` exists in the returned json manifest.

Based on the error message, the timeout (currently 2 minutes) was reached, meaning the created loadbalancer didn't get an IP/hostname within 2 minutes. 

Could you check what happened there? Maybe your openstack had some issues and couldn't provide the IP for the loadbalancer. Or it was just too slow - in this case I could increase the timeout.

**Comment by lklkxcxc** [comment]
@Diaphteiros I used OpenStack cloud platform and Disable loadbalancer IP function . Can I use kubernetes nodeport ？
`kubectl -n kube-system get service nginx-ingress-controller -o json` output:
```
{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "annotations": {
            "dns.gardener.cloud/class": "garden-setup",
            "dns.gardener.cloud/dnsnames": "*.ing.svc.cluster.local",
            "dns.gardener.cloud/ttl": "120",
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{\"dns.gardener.cloud/class\":\"garden-setup\",\"dns.gardener.cloud/dnsnames\":\"*.ing.svc.cluster.local\",\"dns.gardener.cloud/ttl\":\"120\"},\"labels\":{\"app\":\"nginx-ingress\",\"chart\":\"nginx-ingress-0.8.0\",\"component\":\"controller\",\"heritage\":\"Tiller\",\"release\":\"addons\"},\"name\":\"nginx-ingress-controller\",\"namespace\":\"kube-system\"},\"spec\":{\"ports\":[{\"name\":\"http\",\"port\":80,\"protocol\":\"TCP\",\"targetPort\":80},{\"name\":\"https\",\"port\":443,\"protocol\":\"TCP\",\"targetPort\":443}],\"selector\":{\"app\":\"nginx-ingress\",\"component\":\"controller\",\"release\":\"addons\"},\"type\":\"LoadBalancer\"}}\n"
        },
        "creationTimestamp": "2020-03-09T08:10:44Z",
        "labels": {
            "app": "nginx-ingress",
            "chart": "nginx-ingress-0.8.0",
            "component": "controller",
            "heritage": "Tiller",
            "release": "addons"
        },
        "name": "nginx-ingress-controller",
        "namespace": "kube-system",
        "resourceVersion": "69819102",
        "selfLink": "/api/v1/namespaces/kube-system/services/nginx-ingress-controller",
        "uid": "1cfb11a6-09a8-4c93-9ebc-47b5a78feb35"
    },
    "spec": {
        "clusterIP": "10.111.142.171",
        "externalTrafficPolicy": "Cluster",
        "ports": [
            {
                "name": "http",
                "nodePort": 2459,
                "port": 80,
                "protocol": "TCP",
                "targetPort": 80
            },
            {
                "name": "https",
                "nodePort": 3408,
                "port": 443,
                "protocol": "TCP",
                "targetPort": 443
            }
        ],
        "selector": {
            "app": "nginx-ingress",
            "component": "controller",
            "release": "addons"
        },
        "sessionAffinity": "None",
        "type": "LoadBalancer"
    },
    "status": {
        "loadBalancer": {}
    }
}```

**Comment by Diaphteiros** [comment]
I think nodeport could be possible, if you have static worker IPs. garden-setup needs an IP or hostname and will then create a wildcard DNS entry pointing to this domain which is used by multiple other components. 
You will have to tweak garden-setup a little bit:

1. Modify the ingress controller service in the helm chart to use nodeport: https://github.com/gardener/garden-setup/blob/master/components/ingress-controller/chart/templates/00-ingress-controller.yaml#L238-L269 (the values that are given to helm are provided [here](https://github.com/gardener/garden-setup/blob/master/components/ingress-controller/deployment.yaml#L36-L39) in case you want to add something).

2. Modify the ingress-controller component's export file so it doesn't try to fetch a loadbalancer IP anymore. This is this file: https://github.com/gardener/garden-setup/blob/master/components/ingress-controller/export.yaml
```yaml
# don't touch this part
ingresscontroller: (( &temporary ))
env: (( &temporary ))
landscape: (( &temporary ))
settings: (( &temporary ))

# remove temp node completely

export:
  type: A # it's an IP so it needs an A record
  address: # put your static worker IP here
  ingress_domain: (( .settings.ingress_domain ))
```

However, it seems that the Gardener itself also deploys a service of type `LoadBalancer`, for the VPN connection that connects seeds and shoots, so you might run into that problem again. Not sure if it is possible to avoid it. @zanetworker Is it possible to use Gardener without loadbalancer services?
