### ISSUE TITLE
Image for kube-rbac-proxy in terminal-controller-manager to landscape.versions

### ISSUE THREAD

**Issue by dergeberl** [gardener/garden-setup#288]
**What would you like to be added**:

The terminal-controller-manager`manager` image is specified in the `landscape.versions.terminal-controller-manager` but the pod has a second container - `kube-rbac-proxy`

I can`t figure out how to add this to the deployment.yaml from the terminal-controller-manager. 

If I change the edit part in the deployment.yaml as follows, I can change the rbac container but, I don`t know how to specify it to change both containers. 

```yaml
...
  edit:
      path: (( .settings.repo_path ))
      kustomization: "config/default"
      args:
        - set
        - image
        - (( "gcr.io/kubebuilder/kube-rbac-proxy=" .landscape.versions.terminal-controller-manager-rbac.image_repo ":" ( .landscape.versions.terminal-controller-manager-rbac.image_tag || "latest" ) ))
...
```

**Why is this needed**:

To change the `kube-rbac-proxy` image in the `terminal-controller-manager`
