### ISSUE TITLE
OIDC redirect URI is not set correctly by default or via acre.yaml

### ISSUE THREAD

**Issue by hassbert** [gardener/garden-setup#291]
**What happened**: 

While implement OIDC via github dex though an error regarding the redirect URI:
```
time="2020-09-11T13:35:00Z" level=error msg="Connector \"0-git-company-com\" returned error when creating callback: expected callback URL \"https://gardener.ing.my-domain/oidc/callback\" did not match the URL in the config \"https://gardener.ing.my-domain/auth/callback\""
```

Either with or without defined redirectURI in the acre.yaml the callback URL was set to `https://gardener.ing.my-domain/auth/callback` but needs to be set to `https://gardener.ing.my-domain/oidc/callback`.

```
  identity:
    useIdentityDomain: false
    users:
      - email: name@company.email  # email (used for Gardener dashboard login)
        username: name                    # username (displayed in Gardener dashboard)
        password: pass                      # clear-text password (used for Gardener dashboard login)
      - type: github
        id: 0-git-company-com
        name: 0-git-company-com
        config:
          clientID: myID
          clientSecret: mySecret
          # redirectURI: 'https://gardener.ing.mydomain/oidc/callback'
          hostName: git.company.com
          orgs:
            - name: my-org
```
or
```
  identity:
    useIdentityDomain: false
    users:
      - email: name@company.email  # email (used for Gardener dashboard login)
        username: name                    # username (displayed in Gardener dashboard)
        password: pass                      # clear-text password (used for Gardener dashboard login)
      - type: github
        id: 0-git-company-com
        name: 0-git-company-com
        config:
          clientID: myID
          clientSecret: mySecret
          redirectURI: 'https://gardener.ing.mydomain/oidc/callback'
          hostName: git.company.com
          orgs:
            - name: my-org
```
After changing the redirectURI manually in the `identity-configmap` to 'https://gardener.ing.mydomain/oidc/callback' OIDC worked fine.

**What you expected to happen**:
Either set the default redirectURI to `https://gardener.ing.mydomain/oidc/callback` or take over the defined redirectURI from the acre.yaml.

**How to reproduce it (as minimally and precisely as possible)**:

See the identiy part of the acre.yaml above

**Anything else we need to know?**:

No.

**Environment**:

- Version of garden-setup (release or commit): garden-setup 2.3.0 sow version 3.3.0-dev
- Versions of components (only needed if you overwrote the defaults)
- Where does the underlying base cluster come from and which operating system does it use? kops cluster with kubernetes v1.17.11 and default kops images
- Which cloud provider is configured for the setup? aws
