### ISSUE TITLE
Using machineImageDefinitions and machineImages with OpenStack

### ISSUE THREAD

**Issue by berendt** [gardener/garden-setup#319]
The documentation is a bit unclear with this example. I have created an ``acre.yaml``, which works as well.

On the OpenStack environment there is an image with the name ``Ubuntu 20.04`` and with the ID ``c815c712-b125-4ae9-b3b6-efa2a1ed1605``. 

```
| c815c712-b125-4ae9-b3b6-efa2a1ed1605 | Ubuntu 20.04                 | active |
```

I have defined this within the ``iaas`` section as follows:

```
      machineImageDefinitions:
        - name: ubuntu
          versions:
            - version: 20.04.20201016 
              image: Ubuntu 20.04
              regions:
                - name: RegionOne
                  id: c815c712-b125-4ae9-b3b6-efa2a1ed1605
      machineImages:
        - name: ubuntu
          versions:
            - version: 20.04.20201016
```

After deploying the seed with ``sow deploy -A`` this image is also available for selection.

If I try to create a new cluster I cannot select an image and I get the following error: ``Machine Image is required``. The list with the images is empty.

At the moment I am not really sure what is wrongly defined.

Unfortunately I only find the following concrete example: https://github.com/gardener/gardener-extension-provider-openstack/blob/master/example/30-worker.yaml#L27-L34

According to the definition in https://github.com/gardener/garden-setup/blob/master/components/gardencontent/profiles/provider/openstack/iaas.yaml#L27 it should actually fit.

I would like to add to the documentation and get my testbed functional. Any hints? I have tested with version 2.5.0.
