### ISSUE TITLE
Multiple landscape profiles are not supported

### ISSUE THREAD

**Issue by kayrus** [gardener/garden-setup#42]
For some reason only the one profile is handled by the `sow deploy gardencontent/profiles`.

acre.yaml:

```yaml
... ... ...
  profiles:
  - name: region1
    type: openstack
    config:
      floatingPools: (( landscape.iaas.openstack.floatingPools ))
      loadBalancerProviders: (( landscape.iaas.openstack.loadBalancerProviders ))
      machineImages: (( landscape.iaas.openstack.machineImages ))
      machineTypes: (( landscape.iaas.openstack.machineTypes ))
      keystoneURL: (( landscape.iaas.credentials.authURL ))
      zones:
      - region: (( landscape.iaas.region ))
        names: (( landscape.iaas.zones ))
  - name: region2
    type: openstack
    config:
      floatingPools: (( landscape.iaas.openstack.floatingPools ))
      loadBalancerProviders: (( landscape.iaas.openstack.loadBalancerProviders ))
      machineImages: (( landscape.iaas.openstack.machineImages ))
      machineTypes: (( landscape.iaas.openstack.machineTypes ))
      keystoneURL: https://region2
      zones:
      - region: region2
        names: ['az1']
... ... ...
```

In this case only one `region2` profile will be created. If you swap the `region1` and `region2` order, then `region1` will be created, but `region2` will be removed:

```sh
$ sow -v deploy gardencontent/profiles
... ... ...
cluster https://api.ingress:443
  found deployed objects: 2
  found currect objects: 1
  found deployed obsolete objects: 1
    CloudProfile(garden.sapcloud.io/v1beta1): region2
kubectl --kubeconfig landscape/gen/gardencontent/profiles/kubectl/kubeconfig.tmp delete -f landscape-1/gen/gardencontent/profiles/kubectl/manifest.tmp
cloudprofile.garden.sapcloud.io "region2" deleted
generating exports
*** species gardencontent/profiles deployed
```
