### ISSUE TITLE
Automatically Roll Deployments When ConfigMaps/Secrets are changed

### ISSUE THREAD

**Issue by kayrus** [gardener/garden-setup#44]
**What would you like to be added**:

Add a checksum annotation inside the helm deployment templates (pods), e.g.

```yaml
annotations:
  checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
  checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
```

**Why is this needed**:

helm doesn't restart pods, when secrets/configmaps are changed.
