### ISSUE TITLE
Connecting to the AKS cluster fails

### ISSUE THREAD

**Issue by Suse-KevinKlinger** [gardener/garden-setup#472]
**What happened**:
Sow deploy -A times out with "The connection to the server 34.116.146.xxx was refused - did you specify the right host or port?"

**What you expected to happen**:
Sow should deploy the Gardener cluster.

**How to reproduce it (as minimally and precisely as possible)**:

Let's think our Terminal is already in the landscape directory:

1. Create a Service Pricipal in Azure with permissions as Kubernetes admin, storage admin and DNS admin
2. Create a AKS cluster
3. Perform a login with Azure CLI: $az login
4. Get kubeconfig: $az aks get-credentials --resource-group <myResourceGroup> --name <myAKSCluster> --admin
5. Copy the kubeconfig: $cp ~/.kube/config ./kubeconfig
6. Export the kubeconfig: $export KUBECONFIG=./kubeconfig
7. Check access to AKS: $kubectl get nodes
8. Run $sow deploy -A

**Anything else we need to know?**:

**Environment**:
AKS cluster - k8s version = 1.19
Sow version: 3.4.0-dev (commit cef92142c3f4db972f4305997e600501fab2b66f)

My acre.yaml:
```
landscape:
  name: <clusterName>
  domain: <myDomain>

  cluster:
    networks:
      nodes: 10.240.0.4/20
      pods: 10.244.0.0/16
      services: 10.0.0.0/16

  iaas:
    - name: kk-seed1
      type: azure
      region: westeurope
      zones:
        - westeurope
      credentials:
        clientID: <ServicePrincipleID>
        clientSecret: <ServicePrinciplePW>
        subscriptionID: <SubscriptionID>
        tenantID: <TenantID>

  etcd:
    backup:
      type: abs
      resourceGroup: kklinger-gardener-research
      credentials:
        clientID: <ServicePrincipleID>
        clientSecret: <ServicePrinciplePW>
        subscriptionID: <SubscriptionID>
        tenantID: <TenantID>

  dns:
    type: azure-dns
    credentials:
        clientID: <ServicePrincipleID>
        clientSecret: <ServicePrinciplePW>
        subscriptionID: <SubscriptionID>
        tenantID: <TenantID>

  identity:
    users:
      - email: <userMail>
        username: <UserName>
        password: <SecretPW>

  cert-manager:
    email: kevin.klinger@suse.com
    server: self-signed
```

Any ideas?
