### ISSUE TITLE
Dashboard doesn't work with self-signed certificates

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/garden-setup#52]
When trying to login into the dashboard, after entering username and password, one gets redirected to the main page and a red error pops up saying "self-signed certificate in certificate chain". Logging in is not possible.
This doesn't happen when trusted certificates are used (using the letsencrypt live server).

It's probably an error in the dashboard that was introduced with the upgrade to 1.33.0, so https://github.com/gardener/garden-setup/commit/54235048cc774117f2b9543ffdd9ce15d3d86342 should be the last commit that works.

**Comment by Diaphteiros** [comment]
Apparently, it's this commit that broke it: https://github.com/gardener/dashboard/commit/c0d2286c00b9db7ea2edc5dee28d0be41b68abb6

As a temporary workaround, adding
```yaml
        env:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
```
to your dashboard deployment will resolve the problem.

**Comment by Diaphteiros** [comment]
The problem is fixed on the master branch of the dashboard. Until a new release is made, add 
```yaml
  versions:
    dashboard:
      branch: master
      image_tag: "1.34.0-dev-eaffcd26b1663dfa26ba295e9dfca617a287ac00"
```
to the `landscape` node of your acre.yaml to use a working version of the dashboard.
