### ISSUE TITLE
Add an ability to define ClusterRoleBinding for the garden.sapcloud.io:system:project-creation ClusterRole

### ISSUE THREAD

**Issue by kayrus** [gardener/garden-setup#53]
**What would you like to be added**:

By default the project creation is available only for admin: https://github.com/gardener/garden-setup/blob/90980da3eaef4af204776b852d8a64779960f6a0/components/dashboard/deployment.yaml#L89..L97

would be great to have an ability to specify the `ClusterRoleBinding` for:

```
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
```

so every authenticated user can create a project.

**Why is this needed**:

simplify the the landscape setup
