### ISSUE TITLE
Add option to customize Gardener Controller Manager settings

### ISSUE THREAD

**Issue by SimonKienzler** [gardener/garden-setup#745]
**What would you like to be added**:

I'd like to be able to configure various settings for the Gardener Controller Manager.

**Why is this needed**:

These settings should be easily customizable in order to configure the controller manager according to policies and end-user requirements.

**Technical Information**:

I'd be happy to provide this feature, but I wanted to talk about the implementation first. I assume the settings must be added around here:

https://github.com/gardener/garden-setup/blob/f82c6daeb749519bf65bba22d1c1bef86531b7be/components/gardener/virtual/deployment.yaml#L196-L220

So I would introduce a setting option in the `acre.example.yaml`.

```yaml 
landscape:
  ...
  gardener:
    controller:
      config:
        project:
          staleGracePeriodDays: 30
        seed:
          concurrentSyncs: 3
        ...
```

These settings are passed to the `components/gardener/virtual/deployment.yaml`:

```yaml
gardener:
  values:
    global:
      controller:
        config:
          controllers:
            <<: (( merge landscape.gardener.controller.config ))
            ...
```

There are no validators on `landscape.gardener`, so nothing needs to be changed in `acre.yaml`.

Do you agree with this implementation or would you prefer another way of doing it?
