### ISSUE TITLE
Dynamically nested seeds

### ISSUE THREAD

**Issue by kayrus** [gardener/garden-setup#76]
**What happened**:

I'd like to have the following structure:

```
root: (kubernikus cluster)
  seeds:
    - soil:
        seeds:
          - region1
          - region2
```

Unfortunately so far I can create only soil, the seeds inside the soil are not allowed.
